SurveySystem/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SurveySystem.Models
{
    public abstract class Question
    {
        public int Id { get; set; }

        public string Answer { get; set; }
        public List<string> PossibleAnswers { get; set; }

        public abstract string Type { get; }

        public abstract string AppreciationType { get; }

        public string QuestionString { get; set; }

        public virtual ICollection<QuestionGroup> QuestionGroups { get; set; }

        public virtual ICollection<Survey> Surveys { get; set; }

        public Question()
        {
            this.QuestionGroups = new List<QuestionGroup>();
            this.Surveys = new List<Survey>();
            if (Answer != null)
                this.PossibleAnswers = SplitString(Answer);
        }

        public List<string> SplitString(string str)
        {
            List<string> list = new List<string>();
            char delimiter = Convert.ToChar(";");
            string[] splitStrings = str.Split(delimiter);
            foreach (var s in splitStrings)
            {
                list.Add(s);
            }

            return list;
        } 
    }
}

SurveySystem/Models/QuestionGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SurveySystem.Models
{
    public class QuestionGroup
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public virtual ICollection<Question> Questions { get; set; }

        public virtual ICollection<Survey> Surveys { get; set; }

        public QuestionGroup()
        {
            this.Questions = new List<Question>();
            this.Surveys = new List<Survey>();
        }
    }
}

SurveySystem/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using SurveySystem.Models;
using SurveySystem.ViewModels;

namespace SurveySystem.Controllers
{
    [Authorize(Roles = "ADMINISTRATOR, ENQUETEADMINISTRATOR")]
    public class QuestionController : BaseController
    {
        
        // GET: Question
        public ActionResult Index()
        {
            List<QuestionVM> list = new List<QuestionVM>();

            foreach (Question q in Db.ApplicationQuestions.ToList())
            {
                QuestionVM question = CreateQuestionVM(q);
                list.Add(question);
            }
            return View(list);
        }

        // GET: Question/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = Db.ApplicationQuestions.Find(id);
            QuestionVM q = CreateQuestionVM(question);
            if (q == null)
            {
                return HttpNotFound();
            }
            return View(q);
        }

        // GET: Question/Create
        public ActionResult Create()
        {

            QuestionVM question = new QuestionVM();

            return View(question);
        }

        // POST: Question/Create
        [HttpPost]
        public ActionResult Create(QuestionVM questionVm)
        {
            if (ModelState.IsValid)
            {
                Question q;

                if (questionVm.TypeOfAppreciation == "Very bad - Very good")
                {
                    q = new Appreciation();
                    questionVm.Answer = "Very bad;Bad;Good;Very good";
                }
                else if (questionVm.TypeOfAppreciation == "Agreement")
                {
                    q = new Agreement();
                    questionVm.Answer = "Agree;Don't agree;No opinion";
                }
                else if (questionVm.TypeOfAppreciation == "Numerical")
                {
                    q = new Numerical();
                    int counter = 10;
                    string createString = null;
                    for (int i = 1; i <= counter; i++)
                    {
                        createString = createString + i.ToString() + ";";
                    }
                    questionVm.Answer = createString;
                }
                else if (questionVm.TypeOfQuestion == "MultipleValues")
                {
                    MultipleValuesQ mQ = new MultipleValuesQ();
                    q = mQ;
                }
                else if (questionVm.TypeOfQuestion == "OpenEnd")
                {
                    q = new OpenEndQ();
                }
                else if (questionVm.TypeOfQuestion == "PreDefined")
                {
                    PreDefinedQ pQ = new PreDefinedQ();
                    q = pQ;
                }
                else if (questionVm.TypeOfQuestion == "Selection")
                {
                    SelectionQ sQ = new SelectionQ();
                    q = sQ;
                }
                else
                {
                    q = null;
                }
                if (q == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                
                q.QuestionString = questionVm.QuestionString;
                q.Answer = questionVm.Answer;

                Db.ApplicationQuestions.Add(q);
                Db.SaveChanges();
                

                return RedirectToAction("Index");
            }
            
            return View(questionVm);
        }

        // GET: Question/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = Db.ApplicationQuestions.Find(id);
            QuestionVM q = CreateQuestionVM(question);
            return View(q);
        }

        // POST: Question/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, QuestionString, Answer, TypeOfQuestion, TypeOfAppreciation")] QuestionVM questionVm)
        {
            if (ModelState.IsValid)
            {
                Question q = Db.ApplicationQuestions.Find(questionVm.Id);
                if (q.Type == questionVm.TypeOfQuestion)
                {
                    if (q.Type == "Appreciation")
                    {
                        if (q.AppreciationType == questionVm.TypeOfAppreciation)
                        {
                            q.QuestionString = questionVm.QuestionString;
                        }
                        else if (questionVm.TypeOfAppreciation == "Very bad - Very good")
                        {
                            Db.ApplicationQuestions.Remove(q);
                            Db.SaveChanges();
                            Appreciation aQ = new Appreciation();
                            aQ.QuestionString = questionVm.QuestionString;
                            aQ.Answer = "Very bad;Bad;Good;Very Good";
                            q = aQ;
                        }
                        else if (questionVm.TypeOfAppreciation == "Agreement")
                        {
                            Db.ApplicationQuestions.Remove(q);
                            Db.SaveChanges();
                            Agreement aQ = new Agreement();
                            aQ.QuestionString = questionVm.QuestionString;
                            aQ.Answer = "Agree;Don't agree;No opinion";
                            q = aQ;
                        }
                        else if (questionVm.TypeOfAppreciation == "Numerical")
                        {
                            Db.ApplicationQuestions.Remove(q);
                            Db.SaveChanges();
                            Numerical nQ = new Numerical();
                            nQ.QuestionString = questionVm.QuestionString;
                            int counter = 10;
                            string createString = null;
                            for (int i = 1; i < counter; i++)
                            {
                                createString = createString + i.ToString() + ";";
                            }
                            nQ.Answer = createString;
                            q = nQ;
                        }
                    } else
                    {
                        q.QuestionString = questionVm.QuestionString;
                        q.Answer = questionVm.Answer;
                    }
                }
                else if (questionVm.TypeOfAppreciation == "Very bad - Very good" && questionVm.TypeOfQuestion == "Appreciation")
                {
                    Db.ApplicationQuestions.Remove(q);
                    Db.SaveChanges();
                    q = new Appreciation();
                    q.QuestionString = questionVm.QuestionString;

                }
                else if (questionVm.TypeOfAppreciation == "Agreement" && questionVm.TypeOfQuestion == "Appreciation")
                {
                    Db.ApplicationQuestions.Remove(q);
                    Db.SaveChanges();
                    q = new Agreement();
                    q.QuestionString = questionVm.QuestionString;
                }
                else if (questionVm.TypeOfAppreciation == "Numerical" && questionVm.TypeOfQuestion == "Appreciation")
                {
                    Db.ApplicationQuestions.Remove(q);
                    Db.SaveChanges();
                    q = new Numerical();
                    q.QuestionString = questionVm.QuestionString;
                }
                else if (questionVm.TypeOfQuestion == "MultipleValues")
                {
                    Db.ApplicationQuestions.Remove(q);
                    Db.SaveChanges();
                    q = new MultipleValuesQ();
                    q.QuestionString = questionVm.QuestionString;
                    q.Answer = questionVm.Answer;
                }
                else if (questionVm.TypeOfQuestion == "OpenEnd")
                {
                    Db.ApplicationQuestions.Remove(q);
                    Db.SaveChanges();
                    q = new OpenEndQ();
                    q.QuestionString = questionVm.QuestionString;
                }
                else if (questionVm.TypeOfQuestion == "PreDefined")
                {
                    Db.ApplicationQuestions.Remove(q);
                    Db.SaveChanges();
                    q = new PreDefinedQ();
                    q.QuestionString = questionVm.QuestionString;
                    q.Answer = questionVm.Answer;
                }
                else if (questionVm.TypeOfQuestion == "Selection")
                {
                    Db.ApplicationQuestions.Remove(q);
                    Db.SaveChanges();
                    q = new SelectionQ();
                    q.QuestionString = questionVm.QuestionString;
                    q.Answer = questionVm.Answer;
                }

                if (q.Id == questionVm.Id)
                {
                    Db.Entry(q).State = EntityState.Modified;
                }
                else
                {
                    Db.ApplicationQuestions.Add(q);
                }
                
                Db.SaveChanges();

                return RedirectToAction("Index");
            }
            
            return View(questionVm);
 
        }

        // GET: Question/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

SurveySystem/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SurveySystem.Models;
using SurveySystem.ViewModels;

namespace SurveySystem.Controllers
{
    [Authorize(Roles = "ADMINISTRATOR, ENQUETEADMINISTRATOR")]
    public class SurveyController : BaseController
    {
        // GET: Survey
        public ActionResult Index()
        {
            var list = new List<SurveyVM>();

            foreach (var s in Db.ApplicationSurveys.ToList())
            {
                var survey = CreateSurveyVm(s);
                list.Add(survey);
            }

            return View(list);
        }

        // GET: Survey/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var survey = Db.ApplicationSurveys.Find(id);
            var s = CreateSurveyVm(survey);
            if (s == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }

        // GET: Survey/Create
        public ActionResult Create()
        {

            var survey = new SurveyVM();
            survey.AllQuestions = Db.ApplicationQuestions.ToList();
            survey.AllGroups = Db.QuestionGroups.ToList();

            return View(survey);
        }

        // POST: Survey/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title, Description, Active, Comment, SelectedGroups, SelectedQuestions")]SurveyVM s)
        {
            if (ModelState.IsValid)
            {
                var survey = new Survey();
                survey.Title = s.Title;
                survey.Description = s.Description;
                survey.Active = s.Active;
                if (survey.Active)
                {
                    survey.ActiveSince = DateTime.Today;
                }
                survey.Comment = s.Comment;
                foreach (var item in s.SelectedGroups)
                {
                    var g = Db.QuestionGroups.Find(item);
                    survey.QuestionGroups.Add(g);
                }
                foreach (var item in s.SelectedQuestions)
                {
                    var q = Db.ApplicationQuestions.Find(item);
                    survey.Questions.Add(q);
                }

                Db.ApplicationSurveys.Add(survey);
                Db.SaveChanges();

                return RedirectToAction("Index");
            }
                
            return View(s);
            
        }

        // GET: Survey/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var survey = Db.ApplicationSurveys.Find(id);
            var surveyEdit = new SurveyEditVM();
            surveyEdit.Survey = survey;
            surveyEdit.AllGroups = Db.QuestionGroups.ToList();
            surveyEdit.AllQuestions = Db.ApplicationQuestions.ToList();
            return View(surveyEdit);
        }

        // POST: Survey/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Survey, SelectedGroups, SelectedQuestions")]SurveyEditVM surveyEdit)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var survey = Db.ApplicationSurveys.Find(surveyEdit.Survey.Id);
                    survey.Title = surveyEdit.Survey.Title;
                    survey.Description = surveyEdit.Survey.Description;
                    survey.Active = surveyEdit.Survey.Active;
                    if (survey.Active)
                    {
                        survey.ActiveSince = DateTime.Today;
                    }
                    foreach (var item in surveyEdit.SelectedGroups)
                    {
                        var g = Db.QuestionGroups.Find(item);
                        survey.QuestionGroups.Add(g);
                    }
                    foreach (var item in surveyEdit.SelectedQuestions)
                    {
                        var q = Db.ApplicationQuestions.Find(item);
                        survey.Questions.Add(q);
                    }

                    Db.Entry(survey).State = EntityState.Modified;
                    Db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Survey/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var survey = Db.ApplicationSurveys.Find(id);
            var s = CreateSurveyVm(survey);
            if (s == null)
            {
                return HttpNotFound();
            }
            return View(s);
        }

        // POST: Survey/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var survey = Db.ApplicationSurveys.Find(id);
            Db.ApplicationSurveys.Remove(survey);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        public SurveyVM CreateSurveyVm(Survey s)
        {
            SurveyVM survey = new SurveyVM();
            survey.Id = s.Id;
            survey.Title = s.Title;
            survey.Description = s.Description;
            survey.Active = s.Active;
            survey.Comment = s.Comment;
            survey.AllGroups = s.QuestionGroups.Cast<QuestionGroup>().ToList();
            survey.AllQuestions = s.Questions.Cast<Question>().ToList();

            return survey;
        }
    }
}

SurveySystem/Views/SurveyShow/Group.cshtml
@using System.Runtime.InteropServices
@using SurveySystem.Models;

@model SurveySystem.ViewModels.QuestionGroupShowVM

@{
    ViewBag.Title = "Question Group";
}

<h2>@Html.DisplayFor(model => model.QuestionGroup.Title)</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
    @Html.HiddenFor(model => model.Survey)
    @Html.HiddenFor(model => model.CurrentQuestionGroupIndex)
    
    int counter = 0;
foreach (var item in Model.QuestionGroup.Questions)
{
    counter++;
    string name = "answer" + counter;
    <div class="form-group">
        @Html.DisplayFor(modelItem => item.QuestionString)
        <div class="col-md-12">
            @if (item.Type == "Appreciation" || item.Type == "Selection")
            {
                List<string> list = new List<string>();
                char delimiter = Convert.ToChar(";");
                string[] splitStrings = item.Answer.Split(delimiter);
                foreach (var s in splitStrings)
                {
                    list.Add(s);
                }
                foreach (var answer in list)
                {
                    <div class="col-md-1">
                        @Html.RadioButton(name, answer)
                        @Html.DisplayFor(modelItem => answer)
                    </div>
                }
            }
            else if (item.Type == "MultipleValues" || item.Type == "PreDefined")
            {
                Dictionary<string, bool> list = new Dictionary<string, bool>();
                char delimiter = Convert.ToChar(";");
                string[] splitString = item.Answer.Split(delimiter);
                foreach (var answer in splitString)
                {
                    bool b = false;
                    list.Add(answer, b);
                }
                foreach (KeyValuePair<string, bool> boolPair in list)
                {
                    <div class="col-md-4">
                        @Html.CheckBoxFor(modelItem => boolPair.Value)
                        @Html.DisplayFor(modelItem => boolPair.Key)
                    </div>
                }
                if (item.Type == "MultipleValues")
                {
                    <div class="col-md-4">
                        @Html.CheckBox("Other")
                        @Html.DisplayFor(modelItem => modelItem)
                        @Html.EditorFor(model => model)
                    </div>
                }
                }
                else if (item.Type == "OpenEnd")
                {
                    @Html.TextAreaFor(modelItem => item.Answer)
                }
         </div>
    </div>
    <hr/>
}

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Next" class="btn btn-default" />
    </div>
</div>
}

SurveySystem/Views/SurveyShow/Index.cshtml
@model IEnumerable<SurveySystem.Models.Survey>

    @{
        ViewBag.Title = "Index";
    }

    <h2>Choose a survey to start</h2>

    <table class="table">
        <tr>
            <th>
                All active surveys
            </th>
        </tr>

        @foreach (var survey in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => survey.Title)
                </td>
                <td>
                    @Html.ActionLink("Start", "Survey", new { survey.Id }) |

                </td>
            </tr>
        }

    </table>

SurveySystem/Views/SurveyShow/Question.cshtml
@{
    ViewBag.Title = "Question";
}

<h2>Question</h2>

SurveySystem/Views/SurveyShow/QuestionGroupsView.cshtml
@using System.Runtime.InteropServices
@using SurveySystem.Models;

@model SurveySystem.ViewModels.SurveyShowVM

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    int counter = 0;
foreach (var item in Model.QuestionGroupShowVM.CurrentQuestionGroup.Questions)
{
    counter++;
    string name = "answer" + counter;
    <div class="form-group">
        @Html.DisplayFor(modelItem => item.QuestionString)
        <div class="col-md-12">
            @if (item.Type == "Appreciation" || item.Type == "Selection")
            {
                List<string> list = new List<string>();
                char delimiter = Convert.ToChar(";");
                string[] splitStrings = item.Answer.Split(delimiter);
                foreach (var s in splitStrings)
                {
                    list.Add(s);
                }
                foreach (var answer in list)
                {
                    @Html.RadioButton(name, answer)
                    @Html.DisplayFor(modelItem => answer, new { htmlAttributes = new { @class = "form-control" } })
                }
            }
            else if (item.Type == "MultipleValues" || item.Type == "PreDefined")
            {
                Dictionary<string, bool> list = new Dictionary<string, bool>();
                char delimiter = Convert.ToChar(";");
                string[] splitString = item.Answer.Split(delimiter);
                foreach (var answer in splitString)
                {
                    bool b = false;
                    list.Add(answer, b);
                }
                foreach (KeyValuePair<string, bool> boolPair in list)
                {
                    @Html.CheckBoxFor(modelItem => boolPair.Value)
                    @Html.DisplayFor(modelItem => boolPair.Key)
                }
                if (item.Type == "MultipleValues")
                {
                    @Html.CheckBox("Other")
                    @Html.DisplayFor(modelItem => modelItem.QuestionGroupShowVM.OtherAnswer)
                    @Html.EditorFor(model => model.QuestionGroupShowVM.OtherAnswer)
                }
            }
            else if (item.Type == "OpenEnd")
            {
                @Html.TextAreaFor(modelItem => item.Answer)
            }
        </div>
    </div>
}

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Next" name="Next" class="btn btn-default" />
    </div>
</div>
}

SurveySystem/Views/SurveyShow/Survey.cshtml
@using System.Runtime.InteropServices
@using SurveySystem.Models;

@model SurveySystem.ViewModels.SurveyShowVM

@{
    ViewBag.Title = "Survey";
}

<h2>Survey</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Survey.Title)</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Survey.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Survey.Description)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Start", "Group", new { id = Model.Survey.Id })
</p>